####################################################
#                    Cameras                       #
####################################################
- platform: generic
  still_image_url: "https://www.thinkbroadband.com/broadband/monitoring/quality/share/ae25a213af51ed64c2cdf601d17a934194317d36.png"
  name: broadbandquality