###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  customize: !include customize.yaml
  # https://home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages

# Include Files
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
group: !include groups.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
light: !include lights.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

####################################################
#            Home Assistant Components             #
####################################################
# https://www.home-assistant.io/integrations/api/
api:
# https://github.com/Misiu/argon40
argon40:
# https://www.home-assistant.io/integrations/default_config/
default_config:
# https://www.home-assistant.io/integrations/history
history:
# https://home-assistant.io/components/http/
http:
  login_attempts_threshold: 100
# https://www.home-assistant.io/components/logbook/
logbook:
  include:
    domains: 
      - automation
      - script
    entities:
      - binary_sensor.northway_away
# https://www.home-assistant.io/components/logger/
logger:
  default: error
  # logs:
  #   RFXtrx: debug
    # custom_components.sensor.owlintuition: debug
    # custom_components.owlintuition: debug
# https://www.home-assistant.io/docs/ecosystem/ios/
ios:
# https://www.home-assistant.io/components/notify/
# and
# https://www.home-assistant.io/components/notify.group/
notify:
  - name: adults
    platform: group
    services:
      - service: mobile_app_martin_iphonexs
      - service: mobile_app_michelle_iphone_se

  - name: martin
    platform: group
    services:
      - service: mobile_app_martin_iphonexs

  - name: michelle
    platform: group
    services:
      - service: mobile_app_michelle_iphone_se

  - name: morgan
    platform: group
    services:
      - service: mobile_app_morgans_iphone_7
# https://www.home-assistant.io/components/panel_iframe/
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret TasmoAdminURL
# https://www.home-assistant.io/components/recorder/
recorder:
  purge_keep_days: 3
  commit_interval: 60
  # db_url: !secret mariaDbUrl
# https://www.home-assistant.io/components/sun/
sun:
# https://www.home-assistant.io/components/tts/
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  - platform: voicerss
    api_key: !secret voicerss_api_key
    language: "en-gb"
    format: "44khz_16bit_stereo"
