###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  customize: !include customize.yaml

  # https://home-assistant.io/docs/configuration/packages/  
  packages: !include_dir_named packages


####################################################
#        Home Assistant Components Enabled         #
####################################################
# https://www.home-assistant.io/integrations/default_config/
default_config:
# https://www.home-assistant.io/integrations/api/
api:
# https://home-assistant.io/components/http/
http:
  login_attempts_threshold: 100
# https://www.home-assistant.io/docs/ecosystem/ios/
ios:


####################################################
#      Home Assistant Core Components Global       #
####################################################
# https://www.home-assistant.io/components/logbook/
logbook:
  include:
    domains: 
      - automation

# https://www.home-assistant.io/components/logger/
logger:
  default: error
  # logs:
    # homeassistant.components.rfxtrx: debug

# https://www.home-assistant.io/components/recorder/
recorder:
  db_url: !secret mariaDbUrl
  include:
    domains: 
      - automation
# Exclusion based on: https://community.home-assistant.io/t/allow-services-to-be-excluded-from-recorder-and-the-database/115237
  # exclude:
  #   event_types:
  #     - service_removed
  #     - service_executed
  #     - platform_discovered
  #     - homeassistant_start
  #     - homeassistant_stop
  #     - feedreader
  #     - service_registered
  #     - call_service
  #     - component_loaded
  #     - logbook_entry
  #     - system_log_event
  #     - timer_out_of_sync

####################################################
#                     Components                   #
####################################################

# https://www.home-assistant.io/components/panel_iframe/
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret TasmoAdminURL

# https://www.home-assistant.io/components/notify/
# and
# https://www.home-assistant.io/components/notify.group/
notify:
  - name: adults
    platform: group
    services:
      - service: mobile_app_martin_iphonexs
      - service: mobile_app_michelles_iphone

  - name: martin
    platform: group
    services:
      - service: mobile_app_martin_iphonexs

  - name: michelle
    platform: group
    services:
      - service: mobile_app_michelles_iphone

  - name: morgan
    platform: group
    services:
      - service: mobile_app_morgans_iphone_7

# https://www.home-assistant.io/components/tts/
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  - platform: voicerss
    api_key: !secret voicerss_api_key
    language: "en-gb"
    format: "44khz_16bit_stereo"

####################################################
#                     Hardware                     #
####################################################
# https://www.home-assistant.io/components/rfxtrx/
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1K5ML2-if00-port0
  automatic_add: true
  debug: true

####################################################
#                General Automation                #
####################################################
# https://www.home-assistant.io/components/automation/
automation:
  - alias: Sonoff MQTT State Sync
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "sonoffs/cmnd/power"
          payload: ""

  - alias: Update Available Notification
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.martin
      data:
        message: "Update for Home Assistant is available."
