###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  customize: !include customize.yaml

  # https://home-assistant.io/docs/configuration/packages/  
  packages: !include_dir_named packages

####################################################
#        Home Assistant Components Enabled         #
####################################################
# https://www.home-assistant.io/components/automation/
automation: !include automations.yaml
# https://www.home-assistant.io/integrations/default_config/
default_config:
# https://www.home-assistant.io/integrations/api/
api:
# https://home-assistant.io/components/http/
http:
  login_attempts_threshold: 100
# https://www.home-assistant.io/docs/ecosystem/ios/
ios:

####################################################
#      Home Assistant Core Components Global       #
####################################################
# https://www.home-assistant.io/integrations/history
history:
  include:
    entities:
      - sensor.loft_fan_temperature
      - sensor.loft_fan_humidity

# https://www.home-assistant.io/components/logbook/
logbook:
  include:
    domains: 
      - automation

# https://www.home-assistant.io/components/logger/
logger:
  default: error
  # logs:
  #   RFXtrx: debug

# https://www.home-assistant.io/components/recorder/
recorder:
  db_url: !secret mariaDbUrl
  include:
    domains: 
      - automation
    entities:
      - sensor.loft_fan_temperature
      - sensor.loft_fan_humidity

####################################################
#                     Components                   #
####################################################

# https://www.home-assistant.io/components/panel_iframe/
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret TasmoAdminURL

# https://www.home-assistant.io/components/notify/
# and
# https://www.home-assistant.io/components/notify.group/
notify:
  - name: adults
    platform: group
    services:
      - service: mobile_app_martin_iphonexs
      - service: mobile_app_michelles_iphone

  - name: martin
    platform: group
    services:
      - service: mobile_app_martin_iphonexs

  - name: michelle
    platform: group
    services:
      - service: mobile_app_michelles_iphone

  - name: morgan
    platform: group
    services:
      - service: mobile_app_morgans_iphone_7

# https://www.home-assistant.io/components/tts/
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  - platform: voicerss
    api_key: !secret voicerss_api_key
    language: "en-gb"
    format: "44khz_16bit_stereo"
