##################################################
## Lights
##################################################

##################################################
## Lights Groups
##################################################
- platform: group
  name: Morgans Strip Lights
  entities:
    - light.wifi_ufo_1
    - light.wifi_ufo_2
    - light.wifi_ufo_3
    - light.wifi_ufo_4
- platform: group
  name: Morgans Lights
  entities:
    - light.morgans_strip_lights
    - light.lwrf_morgan_main
- platform: group
  name: Frasers Lights
  entities:
    - light.fraser_downlights
    - light.fraser_spotlights
    - light.fraser_nanoleaf