##################################################
## Customize
##################################################
homeassistant:
  customize:
    sensor.kitchen_total_power_now:
      icon: mdi:flash
    sensor.kitchen_total_power_today:
      icon: mdi:counter 
    sensor.kitchen_total_power_cost_today:
      icon: mdi:currency-gbp

##################################################
## Components/Sensors
##################################################
sensor:
  - platform: template
    sensors:
      kitchen_total_power_now:
        value_template: "{{ (states('sensor.dishwasher_power') | float + states('sensor.tumble_dryer_power') | float + states('sensor.washing_machine_power') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Now - Kitchen"
      kitchen_total_power_today:
        value_template: "{{ (states('sensor.dishwasher_power_today') | float + states('sensor.tumble_dryer_power_today') | float + states('sensor.washing_machine_power_today') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Kitchen"
      kitchen_total_power_cost_today:
        value_template: "{{ (states('sensor.kitchen_total_power_today') |float * 0.14284 ) | round(2) }}"
        unit_of_measurement: 'GBP'
        friendly_name: "Power Cost Today - Kitchen"

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.kitchen_total_power_now
      - sensor.kitchen_total_power_today
      - sensor.kitchen_total_power_cost_today

history:
  include:
    entities:
      - sensor.kitchen_total_power_now
      - sensor.kitchen_total_power_today
      - sensor.kitchen_total_power_cost_today