##################################################
## Customize
##################################################
homeassistant:
  customize:
    sensor.tumble_dryer_power:
      icon: mdi:flash
    sensor.tumble_dryer_power_today:
      icon: mdi:flash
    sensor.dryer_status:
      icon: mdi:state-machine

##################################################
## Components/Sensors
##################################################
tplink:
  switch:
    - host: 192.168.170.28 # DHCP reservation

input_select:
  dryer_status:
    name: Tumble Dryer Status
    options:
      - idle
      - running
      - finished
    initial: idle

sensor:
  - platform: template
    sensors:
      tumble_dryer_power:
        value_template: "{{ states.switch.tumble_dryer.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Tumble Dryer Power"
      tumble_dryer_power_today:
        value_template: "{{ states.switch.tumble_dryer.attributes['today_energy_kwh'] | float | round(2) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Tumble Dryer Power Today"
  - platform: template
    sensors:
      dryer_status:
        value_template: "{{ states.input_select.dryer_status.state }}"
        friendly_name: "Tumble Dryer Status"

  - platform: history_stats
    name: Dryer uses today
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dryer uses this week
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

##################################################
## Automation
##################################################
automation:
# When we detect power being drawn from the dryer, above 800W,
# mark the dryer as using started
  - alias: Set dryer active when power detected
    trigger:
      - platform: numeric_state
        entity_id: sensor.tumble_dryer_power
        above: 800
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.dryer_status
          state: 'idle'
        - condition: state
          entity_id: input_select.dryer_status
          state: 'finished'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: 'running'

# When the power level drops below 100W for 3 minutes, and the dryer is set to
# the 'running' state, mark the dryer as finished and send notification.
  - alias: Set dryer drying when power drops
    trigger:
      - platform: numeric_state
        entity_id: sensor.tumble_dryer_power
        below: 100
        for:
          minutes: 3
    condition:
      condition: state
      entity_id: input_select.dryer_status
      state: 'running'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: 'finished'
      - service: notify.michelle
        data:
          message: "Finished!"
          title: "Tumble Dryer"

# Once the dryer status has been 'finished' for 2 minutes, set to idle
  - alias: Set Dryer to idle
    trigger:
      - platform: state
        entity_id: input_select.dryer_status
        to: 'finished'
        for:
          minutes: 2
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: 'idle'

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.dryer_status
      - sensor.tumble_dryer_power
      - sensor.tumble_dryer_power_today

history:
  include:
    entities:
      - sensor.dryer_status
      - sensor.tumble_dryer_power
      - sensor.tumble_dryer_power_today
