##################################################
## Components/Sensors
##################################################
input_select:
  ironing_room_motion_status:
    name: Ironing Room Motion Status
    options:
      - idle
      - motion
    initial: motion

tplink:
  switch:
    - host: 192.168.170.21 # DHCP reservation
    - host: 192.168.170.22 # DHCP reservation
    - host: 192.168.170.23 # DHCP reservation
    - host: 192.168.170.24 # DHCP reservation

sensor:
  - platform: template
    sensors:
      irons_left_power:
        value_template: "{{ states.switch.irons_left.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Room Left"
      irons_left_power_today:
        value_template: "{{ states.switch.irons_left.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room Left"
      irons_right_power:
        value_template: "{{ states.switch.irons_right.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Room Right"
      irons_right_power_today:
        value_template: "{{ states.switch.irons_right.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room Right"
      ironing_table_power:
        value_template: "{{ states.switch.ironing_table.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Table"
      ironing_table_power_today:
        value_template: "{{ states.switch.ironing_table.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Table"
      magpie_iron_power:
        value_template: "{{ states.switch.magpie_iron.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Magpie Iron"
      magpie_iron_power_today:
        value_template: "{{ states.switch.magpie_iron.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Magpie Iron"
      ironing_room_total_power_now:
        value_template: "{{ (states('sensor.irons_left_power') | float + states('sensor.irons_right_power') | float + states('sensor.ironing_table_power') | float + states('sensor.magpie_iron_power') | float) | round(3) }}"
        unit_of_measurement: 'W'
        friendly_name: "Power Now - Ironing Room"
      ironing_room_total_power_today:
        value_template: "{{ (states('sensor.irons_left_power_today') | float + states('sensor.irons_right_power_today') | float + states('sensor.ironing_table_power_today') | float + states('sensor.magpie_iron_power_today') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room"
      ironing_room_power_cost_today:
        value_template: "{{ (states('sensor.ironing_room_total_power_today') |float * 0.14284 ) | round(2) }}"
        unit_of_measurement: 'GBP'
        friendly_name: "Power Cost Today - Ironing Room"
      ironing_room_motion_status: 
        value_template: "{{ states.input_select.ironing_room_motion_status.state }}"
        friendly_name: "Ironing Room Motion Status"

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.ironing_room_motion_status
      - sensor.ironing_room_motion
      - sensor.irons_left_power
      - sensor.irons_left_power_today
      - sensor.irons_right_power
      - sensor.irons_right_power_today
      - sensor.ironing_table_power
      - sensor.ironing_table_power_today
      - sensor.magpie_iron_power
      - sensor.magpie_iron_power_today
      - sensor.ironing_room_total_power_now
      - sensor.ironing_room_total_power_today
      - sensor.ironing_room_power_cost_today

history:
  include:
    entities:
      - sensor.ironing_room_motion_status
      - sensor.ironing_room_motion
      - sensor.irons_left_power
      - sensor.irons_left_power_today
      - sensor.irons_right_power
      - sensor.irons_right_power_today
      - sensor.ironing_table_power
      - sensor.ironing_table_power_today
      - sensor.magpie_iron_power
      - sensor.magpie_iron_power_today
      - sensor.ironing_room_total_power_now
      - sensor.ironing_room_total_power_today
      - sensor.ironing_room_power_cost_today
