##################################################
## Components/Sensors
##################################################
tplink:
  switch:
    - host: 192.168.170.26 # DHCP reservation

input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - idle
      - running
      - finished
    initial: idle

sensor:
  - platform: template
    sensors:
      dishwasher_power:
        value_template: "{{ states.switch.dishwasher.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Dishwasher Power"
      dishwasher_power_today:
        value_template: "{{ states.switch.dishwasher.attributes['today_energy_kwh'] | float | round(2) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Dishwasher Power Today"
  - platform: template
    sensors:
      dishwasher_status:
        value_template: "{{ states.input_select.dishwasher_status.state }}"
        friendly_name: "Dishwasher Status"

  - platform: history_stats
    name: Dishwasher uses today
    entity_id: sensor.dishwasher_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dishwasher uses this week
    entity_id: sensor.dishwasher_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.dishwasher_status
      - sensor.dishwasher_power
      - sensor.dishwasher_power_today

history:
  include:
    entities:
      - sensor.dishwasher_status
      - sensor.dishwasher_power
      - sensor.dishwasher_power_today
