##################################################
## Components/Sensors
##################################################
tplink:
  switch:
    - host: 192.168.170.28 # DHCP reservation

input_select:
  dryer_status:
    name: Tumble Dryer Status
    options:
      - idle
      - running
      - finished
    initial: idle

sensor:
  - platform: template
    sensors:
      tumble_dryer_power:
        value_template: "{{ states.switch.tumble_dryer.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Tumble Dryer Power"
      tumble_dryer_power_today:
        value_template: "{{ states.switch.tumble_dryer.attributes['today_energy_kwh'] | float | round(2) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Tumble Dryer Power Today"
  - platform: template
    sensors:
      dryer_status:
        value_template: "{{ states.input_select.dryer_status.state }}"
        friendly_name: "Tumble Dryer Status"

  - platform: history_stats
    name: Dryer uses today
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dryer uses this week
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.dryer_status
      - sensor.tumble_dryer_power
      - sensor.tumble_dryer_power_today

history:
  include:
    entities:
      - sensor.dryer_status
      - sensor.tumble_dryer_power
      - sensor.tumble_dryer_power_today
