##################################################
## Components/Sensors
##################################################
tplink:
  switch:
    - host: 192.168.170.27 # DHCP reservation

input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - idle
      - running
      - finished
    initial: idle

sensor:
  - platform: template
    sensors:
      washing_machine_power:
        value_template: "{{ states.switch.washing_machine.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Washing Machine Power"
      washing_machine_power_today:
        value_template: "{{ states.switch.washing_machine.attributes['today_energy_kwh'] | float | round(2) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Washing Machine Power Today"
  - platform: template
    sensors:
      washing_machine_status:
        value_template: "{{ states.input_select.washing_machine_status.state }}"
        friendly_name: "Washing Machine Status"

  - platform: history_stats
    name: Washing machine uses today
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Washing machine uses this week
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'


##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.washing_machine_status
      - sensor.washing_machine_power
      - sensor.washing_machine_power_today

history:
  include:
    entities:
      - sensor.washing_machine_status
      - sensor.washing_machine_power
      - sensor.washing_machine_power_today