##################################################
## Components/Sensors
##################################################
sensor:
  - platform: deluge
    host: !secret deluge_host
    port: 58846
    username: !secret deluge_username
    password: !secret deluge_password
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
