##################################################
## Automation
##################################################
automation:
  - alias: HASSIO Weekly Snapshot
    trigger:
      - platform: time
        at: "3:00:00"
    condition:
      condition: time
      weekday:
        - sun
    action:
    - service: hassio.snapshot_full
      data:
        name: "Automated Backup {{ now().strftime('%Y-%m-%d') }}"

  - alias: HASSIO Dropbox Snapshot Sync
    trigger: 
      - platform: time
        at: "4:00:00"
    action:
      - service: hassio.addon_stdin
        data:
          addon: 7be23ff5_dropbox_sync
          input: {"command":"upload"}
