##################################################
## Components/Sensors
##################################################
tplink:
  switch:
    - host: 192.168.170.20 # DHCP reservation - KP115_2 - Irons Left
    - host: 192.168.170.23 # DHCP reservation - HS110_3 - Irons Right
    - host: 192.168.170.24 # DHCP reservation - HS110_4 - Table
    - host: 192.168.170.29 # DCHP reservation - KP115_1 - Magpie Iron

sensor:
  - platform: template
    sensors:
      irons_left_power:
        value_template: "{{ state_attr('switch.irons_left2','current_power_w') }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Room Left"
      irons_left_power_today:
        value_template: "{{ state_attr('switch.irons_left2','today_energy_kwh') | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room Left"
      irons_right_power:
        value_template: "{{ state_attr('switch.irons_right','current_power_w') }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Room Right"
      irons_right_power_today:
        value_template: "{{ state_attr('switch.irons_right','today_energy_kwh') | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room Right"
      ironing_table_power:
        value_template: "{{ state_attr('switch.ironing_table','current_power_w') }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Table"
      ironing_table_power_today:
        value_template: "{{ state_attr('switch.ironing_table','today_energy_kwh') | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Table"
      magpie_iron_power:
        value_template: "{{ state_attr('switch.magpie_iron_kp115','current_power_w') }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Magpie Iron"
      magpie_iron_power_today:
        value_template: "{{ state_attr('switch.magpie_iron_kp115','today_energy_kwh') | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Magpie Iron"
      ironing_room_total_power_now:
        value_template: "{{ (states('sensor.irons_left_power') | float + states('sensor.irons_right_power') | float + states('sensor.ironing_table_power') | float + states('sensor.magpie_iron_power') | float) | round(3) }}"
        unit_of_measurement: 'W'
        friendly_name: "Power Now - Ironing Room"
      ironing_room_total_power_today:
        value_template: "{{ (states('sensor.irons_left_power_today') | float + states('sensor.irons_right_power_today') | float + states('sensor.ironing_table_power_today') | float + states('sensor.magpie_iron_power_today') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room"
      ironing_room_power_cost_today:
        value_template: "{{ (states('sensor.ironing_room_total_power_today') |float * 0.14284 ) | round(2) }}"
        unit_of_measurement: 'GBP'
        friendly_name: "Power Cost Today - Ironing Room"
      ironing_room_motion_status: 
        value_template: "{{ states.input_select.ironing_room_motion_status.state }}"
        friendly_name: "Ironing Room Motion Status"
