##################################################
## Components/Sensors
##################################################
tplink:
  switch:
    - host: 192.168.170.26 # Dishwasher
    - host: 192.168.170.27 # Washing Machine
    - host: 192.168.170.28 # Tumble Dryer

sensor:
  - platform: template
    sensors:
      dishwasher_status:
        value_template: "{{ states('input_select.dishwasher_status') }}"
        friendly_name: "Dishwasher Status"
      dryer_status:
        value_template: "{{ states('input_select.dryer_status') }}"
        friendly_name: "Tumble Dryer Status"
      washing_machine_status:
        value_template: "{{ states('input_select.washing_machine_status') }}"
        friendly_name: "Washing Machine Status"

  - platform: history_stats
    name: Dishwasher uses today
    entity_id: sensor.dishwasher_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dishwasher uses this week
    entity_id: sensor.dishwasher_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Dryer uses today
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dryer uses this week
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Washing machine uses today
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Washing machine uses this week
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

  - platform: template
    sensors:
      kitchen_total_power_now:
        value_template: "{{ (states('sensor.dishwasher_current_consumption') | float + states('sensor.tumble_dryer_current_consumption') | float + states('sensor.washing_machine_current_consumption') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Now - Kitchen"
      kitchen_total_power_today:
        value_template: "{{ (states('sensor.dishwasher_today_s_consumption') | float + states('sensor.tumble_dryer_today_s_consumption') | float + states('sensor.washing_machine_today_s_consumption') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Kitchen"
      kitchen_total_power_cost_today:
        value_template: "{{ (states('sensor.kitchen_total_power_today') |float * 0.17902 ) | round(2) }}"
        unit_of_measurement: 'GBP'
        friendly_name: "Power Cost Today - Kitchen"
