##################################################
## Customize
##################################################
homeassistant:
  customize:
    # Scenes
    scene.bright:
      icon: mdi:lightbulb-on-outline
    scene.comfortable:
      icon: mdi:lightbulb
    scene.movie:
      icon: mdi:movie

##################################################
## Scenes
##################################################
scene:
    # https://www.home-assistant.io/components/scene/
  - name: Bright
    entities:
      light.lwrf_livingroom_main:
        state: on
        brightness: 255
      switch.lwrf_livingroom_standard_lamp: on
      switch.lwrf_displaycabinetlight: on
  - name: Comfortable
    entities:
      light.lwrf_livingroom_main:
        state: on
        brightness: 100
      switch.lwrf_livingroom_standard_lamp: on
      switch.lwrf_displaycabinetlight: on
      switch.lwrf_waxburner: on
  - name: Movie
    entities:
      light.lwrf_livingroom_main:
        state: on
        # Brightness below 27 (~10%) isn't sufficient to turn the light bulbs on
        brightness: 27
      light.lwrf_diningroom_main: off
      switch.lwrf_livingroom_standard_lamp: off
      switch.lwrf_displaycabinetlight: off
      switch.lwrf_diningroom_rennie_mac_lamp: off
