##################################################
## Customize
##################################################
homeassistant:
  customize:
    light.wifi_ufo_1:
      friendly_name: "Desk"
      icon: mdi:led-strip
    light.wifi_ufo_2:
      friendly_name: "Window"
      icon: mdi:led-strip
    light.wifi_ufo_3:
      friendly_name: "Rear Wall"
      icon: mdi:led-strip
    light.wifi_ufo_4:
      friendly_name: "Bed"
      icon: mdi:led-strip
    light.conservatory_desk:
      friendly_name: "Conservatory Desk Strip"
      icon: mdi:led-strip
    light.conservatory_left:
      friendly_name: "Conservatory Ceiling Left"
      icon: mdi:led-strip-variant
    light.conservatory_right:
      friendly_name: "Conservatory Ceiling Right"
      icon: mdi:led-strip-variant

##################################################
## Components/Sensors
##################################################
light:
    # https://www.home-assistant.io/components/light.flux_led/
  - platform: flux_led
    automatic_add: False
    devices:
      192.168.107.20:
        name: wifi_ufo_1
        mode: "rgbw"
      192.168.107.21:
        name: wifi_ufo_2
        mode: "rgbw"
      192.168.107.22:
        name: wifi_ufo_3
        mode: "rgbw"
      192.168.107.23:
        name: wifi_ufo_4
        mode: "rgbw"
      192.168.107.24:
        name: conservatory_desk
        mode: "rgb"
      192.168.107.25:
        name: conservatory_left
        mode: "w"
      192.168.107.26:
        name: conservatory_right
        mode: "w"