##################################################
## Customize
##################################################
homeassistant:
  customize:
    # Scenes
    scene.bright:
      icon: mdi:lightbulb-on-outline
    scene.comfortable:
      icon: mdi:lightbulb
    scene.movie:
      icon: mdi:movie

rfxtrx:
  devices:
    # Lights
    0a1400b303922201100060: # lwrf_diningroom_main
    0a1400ac03922101100060: # lwrf_livingroom_main
    0a14000a03922501100070: # lwrf_morgan_main
    # Switches/Sockets
    0a14000d03922005010080: # lwrf_conservatory_1
    0a14002703922004010080: # lwrf_conservatory_2
    0a14001303922102010080: # lwrf_livingroom_standard_lamp
    0a14001a03922103010080: # lwrf_displaycabinetlight
    0a14001f03922104010080: # lwrf_waxburner
    0a14002403922202010080: # lwrf_diningroom_rennie_mac_lamp
    0a14002903922301010080: # lwrf_hall_socket_1
    0a14002d03922302010080: # lwrf_hall_socket_2
    0a14003e03922401000080: # lwrf_loft_fraser_tv

##################################################
## Scenes
##################################################
scene:
    # https://www.home-assistant.io/components/scene/
  - name: Bright
    entities:
      light.lwrf_livingroom_main:
        state: on
        brightness: 255
      switch.lwrf_livingroom_standard_lamp: on
      switch.lwrf_displaycabinetlight: on
  - name: Comfortable
    entities:
      light.lwrf_livingroom_main:
        state: on
        brightness: 100
      switch.lwrf_livingroom_standard_lamp: on
      switch.lwrf_displaycabinetlight: on
      switch.lwrf_waxburner: on
  - name: Movie
    entities:
      light.lwrf_livingroom_main:
        state: on
        # Brightness below 27 (~10%) isn't sufficient to turn the light bulbs on
        brightness: 27
      light.lwrf_diningroom_main: off
      switch.lwrf_livingroom_standard_lamp: off
      switch.lwrf_displaycabinetlight: off
      switch.lwrf_diningroom_rennie_mac_lamp: off
