##################################################
## Components/Sensors
##################################################
nest:
  # https://www.home-assistant.io/components/nest/
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# HACS: Custom Component
# https://github.com/badguy99/badnest
badnest:
  user_id: !secret badnest_userid
  access_token: !secret badnest_token
  region: eu

climate:
  - platform: badnest
    scan_interval: 10

sensor:
  - platform: template
    sensors:
      hot_water_boost_status:
        friendly_name: "Hot Water Boost Status"
        value_template: "{{ state_attr('water_heater.hallway_thermostat_hot_water', 'boost_mode_status') }}"

water_heater:
  - platform: badnest