##################################################
## Automation
##################################################
automation:
  - alias: Turn on in the morning and sunset
    trigger:
      - platform: time
        at: "06:30:00"
      - platform: sun
        event: sunset
        offset: "-01:00:00"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.lwrf_hall_socket_2 # Twig Lights

  - alias: Turn off after sunrise
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        above: 10.0
    action:
      - service: homeassistant.turn_off
        entity_id: switch.lwrf_hall_socket_2 # Twigs

  - id: '1610821473649'
    alias: Wake up Fraser Light
    description: 15min Sunrise from 7am weekdays
    trigger:
    - platform: time
      at: '7:00'
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
    - service: wled.effect
      data:
        effect: solid # Need to turn off the previous effect, otherwise it doesn't apply.
      entity_id: light.wled_panel_fraser
    - service: wled.effect
      data:
        effect: Sunrise
        intensity: 25
        palette: Default
        speed: 15
      entity_id: light.wled_panel_fraser
    - service: light.turn_on
      entity_id: light.wled_panel_fraser
    mode: single

  - id: '1610821473650'
    alias: Wake up Test Light
    description: 15min Sunrise from 7am weekdays
    trigger:
    - platform: time
      at: '7:00'
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    action:
    - service: wled.effect
      data:
        effect: solid # Need to turn off the previous effect, otherwise it doesn't apply.
      entity_id: light.wled_test2
    - service: wled.effect
      data:
        effect: Sunrise
        intensity: 25
        palette: Default
        speed: 15
      entity_id: light.wled_test2
    - service: light.turn_on
      entity_id: light.wled_test2
    mode: single