##################################################
## Components/Sensors
##################################################
binary_sensor:
  - platform: template
    sensors:
      ensuite_shower_active:
        friendly_name: "Ensuite Shower Active"
        value_template: "{{ states('sensor.ensuite_shower_power') | float > 4.0 }}"
        delay_on:
          seconds: 20
        delay_off:
          seconds: 20
      family_bathroom_shower_active:
        friendly_name: "Familiy Bathroom Shower Active"
        value_template: "{{ states('sensor.family_bathroom_shower_power') | float > 4.0 }}"
        delay_on:
          seconds: 20
        delay_off:
          seconds: 20

sensor:
  - platform: template
    sensors:
      ensuite_shower_minutes:
        friendly_name: "Ensuite Shower Time"
        value_template: "{{ state_attr('sensor.ensuite_shower_time_today', 'value') }}"
      family_bathroom_shower_minutes:
        friendly_name: "Family Bathroom Shower Time"
        value_template: "{{ state_attr('sensor.family_bathroom_shower_time_today', 'value') }}"

  - platform: history_stats
    name: Ensuite Shower Uses Today
    entity_id: binary_sensor.ensuite_shower_active
    type: count
    state: 'on'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Family Bathroom Shower Uses Today
    entity_id: binary_sensor.family_bathroom_shower_active
    type: count
    state: 'on'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Ensuite Shower Time Today
    entity_id: binary_sensor.ensuite_shower_active
    type: time
    state: 'on'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Family Bathroom Shower Time Today
    entity_id: binary_sensor.family_bathroom_shower_active
    type: time
    state: 'on'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
