##################################################
## Components/Sensors
##################################################

sensor:
  - platform: template
    sensors:
      ### WH5 Portable Temperature and Humidity Sensors ###
      portable_sensor_1_temperature:
        value_template: "{{ (states('sensor.temp_humid_1_temperature') | float - 40) | round(1) }}"
        unit_of_measurement: '째C'
        friendly_name: "Temperature (Conservatory)"
      portable_sensor_2_temperature:
        value_template: "{{ (states('sensor.temp_humid_2_temperature') | float - 40) | round(1) }}"
        unit_of_measurement: '째C'
        friendly_name: "Temperature (Living Room)"
      portable_sensor_3_temperature:
        value_template: "{{ (states('sensor.temp_humid_3_temperature') | float - 40) | round(1) }}"
        unit_of_measurement: '째C'
        friendly_name: "Temperature (Fraser)"
      portable_sensor_5_temperature:
        value_template: "{{ (states('sensor.temp_humid_5_temperature') | float - 40) | round(1) }}"
        unit_of_measurement: '째C'
        friendly_name: "Temperature (Morgan)"

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.portable_sensor_1_temperature
      - sensor.portable_sensor_2_temperature
      - sensor.portable_sensor_3_temperature
      - sensor.portable_sensor_5_temperature
      - sensor.temp_humid_ext_1_temperature
      - sensor.temp_sensor_1_temperature

history:
  include:
    entities:
      - sensor.portable_sensor_1_temperature
      - sensor.portable_sensor_2_temperature
      - sensor.portable_sensor_3_temperature
      - sensor.portable_sensor_5_temperature
      - sensor.temp_humid_ext_1_temperature
      - sensor.temp_sensor_1_temperature
