##################################################
## Components/Sensors
##################################################
rfxtrx:
  # RFXCOM 433 Sensors
  devices:
    0a5209e22d000263330179: # Convervatory - Temp_Humid_1
    0a5209070e00026c290189: # Living Room - Temp_Humid_2
    0a5209a82f000265370189: # Frasers Room - Temp_Humid_3
    0a520156c10400f93e0189: # Garden - Temp_Humid_Ext_1
    085002d47502013069:     # Oregon THN132N Temperature - Master Bedroom - Temp_sensor_1

sensor:
  - platform: template
    sensors:
      ### WH5 Portable Temperature and Humidity Sensors ###
      portable_sensor_1_temperature:
        value_template: "{{ (states('sensor.temp_humid_1_temperature') | float - 40) | round(1) }}"
        unit_of_measurement: '째C'
        friendly_name: "Temperature (Conservatory)"
      portable_sensor_2_temperature:
        value_template: "{{ (states('sensor.temp_humid_2_temperature') | float - 40) | round(1) }}"
        unit_of_measurement: '째C'
        friendly_name: "Temperature (Living Room)"
      portable_sensor_3_temperature:
        value_template: "{{ (states('sensor.temp_humid_3_temperature') | float - 40) | round(1) }}"
        unit_of_measurement: '째C'
        friendly_name: "Temperature (Fraser)"
      portable_sensor_5_temperature:
        value_template: "{{ (states('sensor.temp_humid_5_temperature') | float - 40) | round(1) }}"
        unit_of_measurement: '째C'
        friendly_name: "Temperature (Morgan)"

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.portable_sensor_1_temperature
      - sensor.portable_sensor_2_temperature
      - sensor.portable_sensor_3_temperature
      - sensor.portable_sensor_5_temperature
      - sensor.temp_humid_ext_1_temperature
      - sensor.temp_sensor_1_temperature

history:
  include:
    entities:
      - sensor.portable_sensor_1_temperature
      - sensor.portable_sensor_2_temperature
      - sensor.portable_sensor_3_temperature
      - sensor.portable_sensor_5_temperature
      - sensor.temp_humid_ext_1_temperature
      - sensor.temp_sensor_1_temperature
