##################################################
## Automation
##################################################
# automation:
#   - alias: Turn on xmas lights at sunset
#     trigger:
#       - platform: sun
#         event: sunset
#         offset: "-01:00:00"
#     action:
#       - service: homeassistant.turn_on
#         entity_id: switch.lwrf_hall_socket_1 # Outside Socket

#   - alias: Turn off xmas lights at Midnight
#     trigger:
#       - platform: time
#         at: "00:01:00"
#     action:
#       - service: homeassistant.turn_off
#         entity_id: switch.lwrf_hall_socket_1 # Outside Socket
